# Generated by Django 5.1.3 on 2024-11-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_article_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="keywords",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="summary",
            name="review_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="summary",
            name="review_rating",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="summary",
            name="review_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="summary",
            name="review_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="summary",
            name="fact_check",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
