# Generated by Django 5.1.3 on 2024-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_article_keywords_summary_review_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
