# Generated by Django 5.1.3 on 2024-11-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0005_article_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="saved_articles",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="core.article"
            ),
        ),
    ]
